package fi.mobiilikehitysprojektir13.newsapp.screens.country

typealias Language = String
typealias LocaleCode = String

val languages: Map<Language, LocaleCode> = mapOf(
    "Afrikaans" to "af",
    "Albanian" to "sq",
    "Amharic" to "am",
    "Arabic" to "ar",
    "Armenian" to "hy",
    "Assamese" to "as",
    "Azerbaijani" to "az",
    "Bambara" to "bm",
    "Basque" to "eu",
    "Belarusian" to "be",
    "Bengali" to "bn",
    "Bosnian" to "bs",
    "Bulgarian" to "bg",
    "Burmese" to "my",
    "Catalan" to "ca",
    "Central Kurdish" to "ckb",
    "Chinese" to "zh",
    "Croatian" to "hr",
    "Czech" to "cs",
    "Danish" to "da",
    "Dutch" to "nl",
    "English" to "en",
    "Estonian" to "et",
    "Filipino" to "pi",
    "Finnish" to "fi",
    "French" to "fr",
    "Georgian" to "ka",
    "German" to "de",
    "Greek" to "el",
    "Gujarati" to "gu",
    "Hausa" to "ha",
    "Hebrew" to "he",
    "Hindi" to "hi",
    "Hungarian" to "hu",
    "Icelandic" to "is",
    "Indonesian" to "id",
    "Italian" to "it",
    "Japanese" to "jp",
    "Kannada" to "kn",
    "Khmer" to "kh",
    "Kinyarwanda" to "rw",
    "Korean" to "ko",
    "Latvian" to "lv",
    "Lithuanian" to "lt",
    "Luxembourgish" to "lb",
    "Macedonian" to "mk",
    "Malay" to "ms",
    "Malayalam" to "ml",
    "Maltese" to "mt",
    "Maori" to "mi",
    "Marathi" to "mr",
    "Mongolian" to "mn",
    "Nepali" to "ne",
    "Norwegian" to "no",
    "Oriya" to "or",
    "Pashto" to "ps",
    "Persian" to "fa",
    "Polish" to "pl",
    "Portuguese" to "pt",
    "Punjabi" to "pa",
    "Romanian" to "ro",
    "Russian" to "ru",
    "Samoan" to "sm",
    "Serbian" to "sr",
    "Shona" to "sn",
    "Sindhi" to "sd",
    "Sinhala" to "si",
    "Slovak" to "sk",
    "Slovenian" to "sl",
    "Somali" to "so",
    "Spanish" to "es",
    "Swahili" to "sw",
    "Swedish" to "sv",
    "Tajik" to "tg",
    "Tamil" to "ta",
    "Telugu" to "te",
    "Thai" to "th",
    "Turkish" to "tr",
    "Turkmen" to "tk",
    "Ukrainian" to "uk",
    "Urdu" to "ur",
    "Uzbek" to "uz",
    "Vietnamese" to "vi",
    "Welsh" to "cy",
)

/*   If null notice about that user!   */
fun getLanguageCode(languageName: Language): String? = languages[languageName]